### ISSUE TITLE
Seldon Core conversion

### ISSUE THREAD

**Issue by cliveseldon** [kubeflow/manifests#10]
We'd like to convert the Seldon KSonnet components. Happy to do a PR for this. Any advice/docs on what you did for the existing components to convert them?

**Comment by swiftdiaries** [comment]
I did a `ks show <environment name> -c <component name> > component.yaml` 
And then for the directory layout, I think you can look at the existing manifests and model them around that.
We currently bake in most of the ksonnet parameters so that the resulting manifest is more or less ready to use off the shelf

**Comment by swiftdiaries** [comment]
But I think long term, we need to think about providing a converter so that we can ease migration for end-users like David mentioned at the community meeting.

**Comment by jlewi** [comment]
@cliveseldon any chance you could pick this up in the next day or two? Hopefully it should be pretty straightforward.

**Comment by cliveseldon** [comment]
There is a PR #36 to add Seldon Kustomize waiting for approval - plus one in kubelow https://github.com/kubeflow/kubeflow/pull/3527

I was following the notes provided kindly by @kkasravi

**Comment by jlewi** [comment]
#36 was merged so I'm closing this out.
