### ISSUE TITLE
oidc authentication EnvoyFilter should not use default ingress

### ISSUE THREAD

**Issue by apryiomka** [kubeflow/manifests#1191]
When we enable authentication, it selects default istio ingress gateway that effectively enables authentication for the entire cluster including the KFServing inference services. Inference services should have their own way of authentication that can be different from the default Kubeflow authentication. For example, we may choose to use single OpenID provider for Kubeflow, but something else, like OAuth for inference service. Currently there is no easy way to configure inference service to use something else or not to use authentication at all.

**Comment by yanniszark** [comment]
Hi @apryiomka!
You can configure the EnvoyFilter to apply to only a single host.
There is a wide selection of options, you can see them here:
https://istio.io/docs/reference/config/networking/envoy-filter/
Alternatively, you can rollout a separate Istio Gateway for KFServing.
Do these options satisfy your use-case?

**Comment by apryiomka** [comment]
@yanniszark link to istio documentation doesn't help. First of all, the current filter is not written in the new format, I would have to rewrite the filter from scratch. The reported issue is describing the current kubeflow behavior that is flowed in my opinion, a link to istio docs doesn't fix anything. 

If you have an example of how to rewrite the filter, please share the example or create a PR to merge that in. 

Thanks you.

**Comment by apryiomka** [comment]
> Alternatively, you can rollout a separate Istio Gateway for KFServing.

Currently the filter is applied to the default ingress, adding a gateway that uses the same ingress wouldn't not address the issue. The issue is that we shouldn't apply kubeflow UI filter to the default ingress, but rather to the kubeflow virtual services. The problem with kubeflow virtual services is that they don't inject sidecars meaning we cannot really apply the filter directly to the UI compontents.

**Comment by yanniszark** [comment]
@apryiomka lots of information here, let me try to answer.

> The problem with kubeflow virtual services is that they don't inject sidecars into the pods meaning we cannot really apply the filter directly to the UI components since envoy filters apply to the envoys and we don't run any for kubeflow UI.

You're right, injecting all components with Istio sidecars is still a work-in-progress. Currently, authentication and authorization in Kubeflow is designed to work at the gateway level. When most components are able to use Istio sidecars, we should be able to discuss solutions that apply at the sidecar level.

Since it's applied at the Gateway level, the question is how do we apply it? Some users may want to use the Gateway just for Kubeflow, some may use a specific host for Kubeflow (`kubeflow.example.org`), some may allocate a path for Kubeflow (`/kubeflow`) or a combination of the two. What I am seeing is that at that point, the user should configure the EnvoyFilter in a way that matches their environment.

> If you have an example of how to rewrite the filter, please share the example

A community member (slack handle `Abdul`) recently [shared an example in Slack](https://kubeflow.slack.com/archives/C7REE0EHK/p1591113336205800?thread_ts=1590584519.159200&cid=C7REE0EHK) on how to disable a filter on a specific host. A similar logic can be used for enabling a filter on a specific host.

**Comment by marcinkosztolowicz** [comment]
> A community member (slack handle `Abdul`) recently [shared an example in Slack](https://kubeflow.slack.com/archives/C7REE0EHK/p1591113336205800?thread_ts=1590584519.159200&cid=C7REE0EHK) on how to disable a filter on a specific host. A similar logic can be used for enabling a filter on a specific host.

Could you provide this example here in this issue discussion. I do not have access to kubeflow slack channel

**Comment by juliusvonkohout** [comment]
Kubeflow 1.9.1/1.10 switched to oauth2-proxy, so please just upgrade. Envoyfilter is gone.

**Comment by juliusvonkohout** [comment]
> > > 一位社区成员（Slack 用户名`Abdul`）最近[在 Slack 上分享了一个关于](https://kubeflow.slack.com/archives/C7REE0EHK/p1591113336205800?thread_ts=1590584519.159200&cid=C7REE0EHK)如何在特定主机上禁用过滤器的示例。类似的逻辑也适用于在特定主机上启用过滤器。
> > 
> > 
> > 你能在这个 issue 讨论中提供这个例子吗？我无法访问 kubeflow slack 频道。
> 
> Me too. I don't have an account to log in to Slack

Then please join https://www.kubeflow.org/docs/about/community/
