### ISSUE TITLE
Port spark operator manifest to kustomize

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#122]
We have a ksonnet manifest for spark here:
https://github.com/kubeflow/kubeflow/tree/master/kubeflow/spark

@holdenk @rawkintrevo what are your thoughts on whether we should port this to kustomize or not?

If a user wants to install and use the spark-operator with Kubeflow it seems perfectly reasonable to point them at the i[nstructions] (https://github.com/GoogleCloudPlatform/spark-on-k8s-operator) for how to install it on a K8s cluster. 

I think we only need a kustomize manifest if we want to be able to install spark operator by default as part of one/or more opinionated deployments of Kubeflow. 

For example, if/when TFX works on spark, if we have a whole bunch of applications that we want to install in order to create a Kubeflow+Spark+TFX deployment. Then we need to figure out a a better story for how to compose applications.  But right now I think we are still using Spark as an opptional add on.

Thoughts?

**Comment by holdenk** [comment]
I'm happy to do the port. I think having a tool to do distributed data prep that isn't tied to GCP is useful. cc @texasmichelle

**Comment by jlewi** [comment]
@holdenk sounds good.

FYI; The Flink Operator would also be useful https://github.com/lyft/flinkk8soperator.

In the near term, Flink is the most viable option for running Beam and thus TFX off GCP. (see also  kubeflow/kubeflow#1583)

**Comment by holdenk** [comment]
I agree Flink would be useful for supporting TFX off GCP but I think given the lack of reasonable Beam Flink Python support that for people building data pipelines in the next year or so that isn't a realistic option. But once Beam Flink Python works well I think making an opperator to allow submissions of Beam jobs to either Flink or Dataflow would be of great use in allowing portable TFX pipelines to work well on Kubeflow (left a comment on 1583 about this).

**Comment by jlewi** [comment]
@holdenk any update on this?

**Comment by holdenk** [comment]
This has been finished.
/close
