### ISSUE TITLE
Make an E2E test for manifests

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/manifests#1244]
Since #1237 removes the erstwhile GCP cluster-based E2E test. We might need an E2E test to:

1. Ensure that dependencies within the manifest definitions are maintained and are deployed in order.
1. All required custom resources definitions are created before the CRs are applied
1. Ensure that common services defined in manifests remain functional

The bar for this E2E test would be:
1. The test is fast and reliable
1. That the test is catching breakages that would otherwise be missed

**Comment by jlewi** [comment]
Per my [comment](https://github.com/kubeflow/manifests/pull/1237#issuecomment-642119697), I think the question is what tests should happen upstream vs. downstream?

For GCP our plan is to move the E2E tests downstream kubeflow/gcp-blueprints#42. We are doing this because I think we need better separation of concerns.

The manifests themselves should largely be owned and maintained by the application OWNERs. 

It seems like the areas you want to test are mostly about deployment which I think should be a downstream concern.

Deploying kubeflow seems like a two step process

```
kustomize build | kubectl apply 
```

Should testing reflect that? So tests for kubeflow/manifests should be focused on ensuring that `kustomize build` produces the correct output. Testing that the manifests get applied correctly seems like it should be the responsibility of platform/distribution owners. For example, ensuring manifests are applied in the correct order will depend on the deployment tooling used which will vary by platform.

Likewise ensuring that configuration is correct in terms of integrating with external systems seems like it should be the responsibility of platform owners. e.g. testing that on GCP pipelines is actually configured to talk to CloudSQL should happen downstream or at best the test should be tightly scoped so that unless you are directly changing the GCP configs the code doesn't get triggered.

> Ensure that common services defined in manifests remain functional

What do you mean by common service?

**Comment by krishnadurai** [comment]
Most of my concerns are deployment concerns.

It may benefit us to have a conformance test with a neutral platform (like KinD) apart from the downstream tests with vendors. This will help us in having a deployment validity check in CI before a merge of a PR to master.

> What do you mean by common service?
Services like cert-manager, Istio etc fall under this bracket.

**Comment by PatrickXYS** [comment]
This is finished I think

/close
