### ISSUE TITLE
argo-workflows should be top-level in kfdef files

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/manifests#1547]
Users may already have an install of `argo-workflows` installed in their Kubernetes cluster.

Therefore, we should move the `argo` out of the `./stacks/*/kustomization.yaml` and into the root `./kfdef/*.yaml`

This is similar to what we already do for `isio` and `cert-manager`, and will let providers include **newer versions** of `argo-workflows`.

**Comment by thesuperzapper** [comment]
Tagging pipeline people: @Bobgy @IronPan @rmgogogo

**Comment by rmgogogo** [comment]
How about remove the existing installation and then KF?
Or to different namespace for isolation?

**Comment by thesuperzapper** [comment]
@rmgogogo, what are you saying?

I am talking about making it easier for users to NOT deploy the manifests described in: [manifests/argo/*](https://github.com/kubeflow/manifests/tree/master/argo), and instead make use of an existing argo-workflow installation.

Unless you are saying current-state is not that big of an issue because we are installing the `argo-workflows` controller into the `kubeflow` namespace? (In which case, note that things like CRDs are still cluster wide, and may change between `argo-workflow` versions)

**Comment by rmgogogo** [comment]
I think we are talking same thing.

1. CRD is shared cross cluster
2. You have an existing Argo operator installed.
3. You install KF but it also contains an Argo operator.
4. You prefer move it so that KF installation can use existing Argo.

Right?

My concern is that it's possible certain Argo version is not tested together with Pipeline. That's why I give previous reply.

@Bobgy may give better answer.

**Comment by Bobgy** [comment]
I agree with @rmgogogo in that the argo configmap is highly-coupled to Kubeflow Pipelines: https://github.com/kubeflow/manifests/blob/3fd1c711430b6d676b93cdf6008e1baa75bcd89d/argo/base/params.env

But the upgrade problem is a valid ask, I believe we should think about a way people can come and customize things in stacks too. They might want to upgrade KFP, KFServing, etc, because Kubeflow release cycle is long.

Considering kustomize's recommendation of composing stuff, does it make sense to ask users fork the `stacks/xxx/kustomization.yaml` and choose which components they want?

**Comment by Bobgy** [comment]
@thesuperzapper we can bring this topic to deployment wg's discussion

**Comment by yanniszark** [comment]
Closing as we have moved to an updated layout for manifests
