### ISSUE TITLE
Should we remove E2E tests from manifests repo

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#1613]
This test
https://github.com/kubeflow/manifests/blob/3f9398f926cc117eedc214ca5fa1c8412fb605c4/prow_config.yaml#L15

I'm not sure why we still have it. See #818 for more context about fixing the test.

Also see the recent discussion [here](https://github.com/kubeflow/manifests/pull/1609#pullrequestreview-523934468)

/cc @PatrickXYS @kubeflow/wg-manifests-leads

**Comment by Bobgy** [comment]
Totally agree, I'd suggest moving the e2e test to postsubmit/periodic, because it is slow and can be flaky.

Previously we had a unit test for manifests repo by just generating all the targets and compare with snapshots. I think that's better for unit testing, because it makes all effects of the changes visible. Right now, after https://github.com/kubernetes/test-infra/pull/19833, we are losing that unit test.

FYI, the unit test can be run by `cd tests; make test`.

**Comment by PatrickXYS** [comment]
> Right now, after kubernetes/test-infra#19833, we are losing that unit test.

We are not losing the unit test, we still enable it in AWS CI, https://github.com/kubeflow/manifests/blob/master/prow_config.yaml#L9-L15

But I agree that we need to think about E2E test, propose some optimization etc. I'll discuss this topic after 1.2

**Comment by yanniszark** [comment]
I believe we've removed e2e tests, so closing...
