### ISSUE TITLE
Why do we need kubernetes-sigs/application controller in Kubeflow?

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/manifests#1715]
When I was investigating issue: https://github.com/kubeflow/gcp-blueprints/issues/184,

I realized there's a huge volume of logs coming from application controller, and so far I think that's normal behavior, we need a way to change log level, but I don't think it exposed such a config.

However, a bigger question is why is Kubeflow using application controller? Does it solve anyone's problem? It seems https://github.com/kubernetes-sigs/application doesn't have much activity any more.

> As a developer, I almost never look at application CRs, because I know the low-level details. There doesn't seem to be enough UI/guidance that teach entrance level people to use them.

This is what I feel about it, I'd like to know more context.

/cc @jlewi @kubeflow/wg-deployment-leads

**Comment by Bobgy** [comment]
Additionally, I think we've got many issues with application maintenance like https://github.com/kubeflow/manifests/issues/1573, no one before `thesuperzapper` noticed the problem seems to be an evidence that no one used it at all.

**Comment by Bobgy** [comment]
Sorry, I mentioned the wrong group.
I meant @kubeflow/wg-manifests-leads, not `@kubeflow/wg-deployment-leads`, but maybe it's worth both groups' discussion.

**Comment by yanniszark** [comment]
@Bobgy you ninja'd me there, I was planning to ask this question myself in the doc we're preparing for manifests best practices, as mentioned here: https://github.com/kubeflow/manifests/issues/1710

It could also lead to weird and hard-to-debug issues, like the one seen here:
https://github.com/kubeflow/manifests/issues/540
https://github.com/kubeflow/kubeflow/issues/4767#issuecomment-586752595

If adding cluster-wide resources by mistake to an Application CR can lead to resources being accidentally deleted, this is very worrying by itself.

As to the value it provides, it enables users to see and handle the high-level apps installed in the cluster. However, given the inactivity of the upstream repo (https://github.com/kubernetes-sigs/application) and the limitations it has (what about cluster-level resources?, excessive logging), I don't know if it makes sense to prescribe this everywhere.

**Comment by Bobgy** [comment]
Haha, good to know you have also thought of it.

**Comment by yanniszark** [comment]
I prepared a small overview of the application cr in Kubeflow.

**What is it used for:**
- The ability to describe an applications metadata (e.g., that an application like notebook-controller is running). This is why the GKE marketplace demands it.
- Tying all configuration (e.g., CRDs, Deployments, etc) relevant to an App together. It doesn't support cross-namespace references.

**Limitations:**
- It selects resources by labels and then adds ownerReferences to the Application CR (optional, but we have it turned on everywhere). This means it can't select resources in many namespaces OR cluster-level resources. Selecting a cluster-level resource can cause silent damage (https://github.com/kubeflow/manifests/issues/540)
- The application-controller produces tons of logs, causing big bills for unexpecting users (https://github.com/kubeflow/gcp-blueprints/issues/184). Is this perhaps affecting us as well?
- It needs to be constantly updated with all the resource kinds that it must watch, instead of inferring them from the labels. This leads to it going out-of-sync (https://github.com/kubeflow/manifests/issues/1573).
- It hasn’t picked up much traction and the repo is light on activity.
Because of these, the second point is pretty much nil. The Application CR fails to select and anchor all relevant config to it. The only remaining point is that it packages some metadata about an application.


**Proposed Solution**
The Application CR has failed to achieve its goals. It is an extra maintainance burden, so we should remove it.
@bobgy what do you think? Perhaps we should have a quick slot one of these days to discuss further?

**Comment by Bobgy** [comment]
I agree with that, plus.. we may use kpt live status instead for the monitoring functionality.

**Comment by thesuperzapper** [comment]
@yanniszark  agree with removal, but since its the responsibility of component owners to do this, we should do a quick run through before the 1.3 release to check everyone has removed them

**Comment by akdigitalself** [comment]
Thanks for giving a background on this issue. The other issues where this issue is referenced are resolved. The application manifest [exists](https://github.com/kubeflow/manifests/tree/v1.3-branch/contrib/application) in the 1.3 branch. Is there a plan to remove it in v1.3.1?

**Comment by yanniszark** [comment]
@akdigitalself the application controller exists under `contrib`, which contains 3rd-party packages not supported by a Kubeflow WG. But yes, we should clean it up for 1.4. Would you like to open a PR for that?

**Comment by juliusvonkohout** [comment]
I am always disabling it in my installation.  Is it just about removing manifests/contrib/application/ ? Then i can create a pull request to just delete that folder.

**Comment by juliusvonkohout** [comment]
metacontroller is also something that seems quite useless.

**Comment by Bobgy** [comment]
Some installations need it, so we don't want to remove it yet. It's already not included in platform-agnostic

**Comment by juliusvonkohout** [comment]
> 
> 
> Some installations need it, so we don't want to remove it yet. It's already not included in platform-agnostic

@Bobgy are you sure that you did not accidentally leave it in ? https://github.com/kubeflow/manifests/blob/18b9bc8d2d98d62c241c2a68e2b2effb8b0222b2/apps/pipeline/upstream/env/platform-agnostic-multi-user/kustomization.yaml#L13

**Comment by Bobgy** [comment]
@juliusvonkohout that's metacontroller, not application controller.
https://github.com/metacontroller/metacontroller is a dependency of KFP profile controller.

**Comment by juliusvonkohout** [comment]
@Bobgy 

the first thing i do is not installing metacontroller, so i do not see how it is needed for Kubeflow pipelines. 

1. It generates 30 Megabyte logfiles in 10 minutes
2. it runs a root and privileged container
3. With enormous CPU (1-4) and memory (1-4 Gi) requests.
4. Furthermore the project has not been maintained for two years

The profile controller still seems to work properly. Can you explain why metacontroller is needed.

https://github.com/GoogleCloudPlatform/metacontroller "This repository has been archived by the owner. It is now read-only. "
