### ISSUE TITLE
google cloudsql metadata deployment duplicate definition

### ISSUE THREAD

**Issue by gregbarkerdcsg** [kubeflow/manifests#1716]
[manifests/metadata/overlays/google-cloudsql/metadata-deployment.yaml](https://github.com/kubeflow/manifests/blob/e1441603ab359b1a816f91882742fc041a5e12f8/metadata/overlays/google-cloudsql/metadata-deployment.yaml#L1) has 2 duplicate deployment definitions. The top one references a deployment named "deployment" and server named "server". The bottom one references the correct deployment, grpc-deployment and grpc-server. I think the top definition can be deleted. It worked for me anyway.

Thanks.

**Comment by Bobgy** [comment]
Your understanding is correct.

but we removed the entire folder, because the instructions are no longer the recommended process to build that setup.
https://github.com/kubeflow/manifests/pull/1718

**Comment by gregbarkerdcsg** [comment]
@Bobgy what is the recommended process to build that setup? This, manifests/pipeline/upstream/sample?

**Comment by Bobgy** [comment]
We haven't built an example yet, when we release built-in support for using CloudSQL, some difference from the current one:
1. the CloudSQL instance will be provisioned with manifests like other GCP infra
2. instead of using Google service account credentials, we'll leverage workload identity to give the CloudSQL proxy permissions it needs

If you want to deploy with CloudSQL right now, you can make your own decision about 1, but we still recommend using workload identity, there are service accounts deployed with Kubeflow that already has workload identity bindings, you might use them for a quicker start, but you can choose to deploy everything from whatever your opinionated way too.

**Comment by Bobgy** [comment]
@gregbarkerdcsg
