### ISSUE TITLE
Error on Kustomize Build

### ISSUE THREAD

**Issue by matty1979** [kubeflow/manifests#1799]
Trying to run these as normal kustomize files using the example 

```
$ kustomize build
Error: accumulating resources: accumulation err='accumulating resources from '../common/cert-manager/cert-manager-kube-system-resources/base': evalsymlink failure on '/Users/matthewking/Downloads/common/cert-manager/cert-manager-kube-system-resources/base' : lstat /Users/matthewking/Downloads/common: no such file or directory': evalsymlink failure on '/Users/matthewking/Downloads/common/cert-manager/cert-manager-kube-system-resources/base' : lstat /Users/matthewking/Downloads/common: no such file or directory
```

Unable to build or run. 
However, if I go individually file by file, like 

```
kustomize build  common/istio-1-9-0/istio-crds/base | kubectl apply -f -
kustomize build  common/istio-1-9-0/istio-namespace/base | kubectl apply -f -
kustomize build  common/istio-1-9-0/istio-install/base | kubectl apply -f -
```
It works correctly and I have a working kubeflow, installed on my EKS Cluster.

**Comment by DavidSpek** [comment]
It looks like you are having issues with the cert-manager manifests specifically. Is that indeed the case? You could try the manifests I made that deploy cert-manager 1.2 rather than those in this repo that deploy 0.11. https://github.com/kubeflow-onprem/ArgoFlow/tree/master/cert-manager. 

You should just be able to execute `kustomize build github.com/kubeflow-onprem/ArgoFlow/cert-manager | kubectl apply -f -`.

**Comment by yanniszark** [comment]
@matty1979 thanks for opening an issue. Can you give the commands you ran?
Checking out the latest release candidate (`v1.3.0-rc.0`) and running kustomize as per the README:
`kustomize build --load_restrictor=none example`
should work.

Did I misunderstand your problem? What commands are you running? Can you confirm your kustomize version is `3.2.0`?

**Comment by DavidSpek** [comment]
I think the issue might be not using the load restrictor flag and targeting https://github.com/kubeflow/manifests/tree/master/common/cert-manager/cert-manager/kubeflow-issuer which needs this flag. This folder seems useless and targeting https://github.com/kubeflow/manifests/blob/master/common/cert-manager/cert-manager/overlays/self-signed directly would remove the need for the load-restrictor flag.

**Comment by matty1979** [comment]
I omitted the --load_restrictor=none because it just errored out so I just kept going to see what I could get to work. 
Will try installing via argo and will go from there.

**Comment by DavidSpek** [comment]
@matty1979 Using kustomize and kubectl should work as this is what Argo CD essentially does as well, but it might be easier to manage and debug things with Argo CD (the UI is very powerful). If you need any help you can create an issue [here](https://github.com/kubeflow-onprem/ArgoFlow/issues) or send me a message on Slack and I'll be happy to help you get setup.

**Comment by matty1979** [comment]
Utilizing Argo and the build and actually following instructions, I have it running except knative as it reads as degraded. 
Still trying to figure out the ingress for AWS Certs etc, but as far as installation, following this fixes my original issue.

**Comment by DavidSpek** [comment]
@matty1979 KNative it might be the autoscaler causing the app to be set to degraded.
If you click on the KNative application you can see which resources are degraded. You can the click on a resource to see things like events, logs, the deployed manifest, the diff if it is out of sync, etc.
If it indeed is the autoscaler, it just took a while for it to become ready on my cluster. Otherwise you can try and delete it and it will get recreated by Argo CD. If that doesn’t help, please send me a message or create an issue so I can look into it more closely.

**Comment by matty1979** [comment]
Will update with what I find. Already tore down cluster and building a smaller one using spot instances instead of running 24/7

**Comment by DavidSpek** [comment]
@matty1979 I forgot to mention that the autoscaler for KNative requires the metrics-server to be installed on the cluster as wel.

**Comment by matty1979** [comment]
Interesting, that's only mentioned in the docs if installing via kind.

**Comment by DavidSpek** [comment]
Good catch, I'll add that to the README.
