### ISSUE TITLE
jupyter-web-app: add userid-header and userid-prefix cli flags to parameters

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#180]
Sub-issue for https://github.com/kubeflow/kubeflow/issues/3553.
Add parameters to configure:
* Which header we read for the user info (now it's only X-Goog-Authenticated-User-Email)
* What prefix is expected (now it's expected to be in the form of accounts.google.com:<user>, so the prefix is accounts.google.com:)

These are controlled by the cli flags `userid-header` and `userid-prefix`.

/priority p0

cc @jlewi @kimwnasptd

**Comment by jlewi** [comment]
@kimwnasptd based on kubeflow/kubeflow#3556 what is the current status of identity awareness in the jupyter-web-app?

Is the jupyter-web-app enforcing some kind of access check that won't pass if the request doesn't contain the email?

Is there a way to disable auth checks in the jupyter web app?

**Comment by jlewi** [comment]
Looks like @kimwnasptd already answered my question [here](https://github.com/kubeflow/kubeflow/issues/3556#issuecomment-509717702)

IIUC the web app should gracefully handle the case where no user id is provided. 

Therefore I think we can downgrade this to P1 because I don't think its release blocking

* On platforms where the userid header and prefix aren't set it will just fall back to not enforcing the check
* Since the web app has already been updated in kubeflow/kubeflow#3556 people can always work around this issue by manually updating their kustomize package.
