### ISSUE TITLE
No response from kfserving predict

### ISSUE THREAD

**Issue by botasb** [kubeflow/manifests#1897]
I have installed Kubeflow in minikube with the script provided here. Everything installed without issues.
I have created a custom model for kfserving. I tested it runing the docker locally and got the predictions as expected.
I deploy the custom model as instructed in https://github.com/kubeflow/kfserving . The service is deployed and I can see the url and READY status. 
I  port forward correctly (_INGRESS_GATEWAY_SERVICE=$(kubectl get svc --namespace istio-system --selector="app=istio-ingressgateway" --output jsonpath='{.items[0].metadata.name}')
kubectl port-forward --namespace istio-system svc/${INGRESS_GATEWAY_SERVICE} 8080:80_)
But when I call the predict service I get NO ERROR, but no reponse either:

 _curl -v -H "Host: kfserving-custom-model.default.example.com" http://localhost:8080/v1/models/kfserving-custom-model:predict  -d @./input_data_v4.json 
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /v1/models/kfserving-custom-model:predict HTTP/1.1
> Host: kfserving-custom-model.default.example.com
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 1634490
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 302 Found
< location: /dex/auth?client_id=kubeflow-oidc-authservice&redirect_uri=%2Flogin%2Foidc&response_type=code&scope=profile+email+groups+openid&state=MTYyMzIzNTA4OHxFd3dBRUU0NU5WSjRVbFJhU0ZkVmMyRkVOa2c9fDmRmFavDhm0RwXVy5cx7Rs6QlStKDdWqaezXnT6NG3D
< date: Wed, 09 Jun 2021 10:38:08 GMT
< x-envoy-upstream-service-time: 12
< server: istio-envoy
< connection: close
< content-length: 0
< 
* Closing connection 0_

All this running locally in my PC.

Any idea what could be the issue?
Thanks

**Comment by yanniszark** [comment]
@botasb it's possible that your issue is: https://github.com/kubeflow/kfserving/issues/1558
Please try one of the solutions mentioned in the issue above:
- Disable sidecar injection with `sidecar.istio.io/inject: false`
- Apply an AuthorizationPolicy in the `kubeflow-user` namespace to allow certain Knative traffic: https://github.com/kubeflow/kfserving/issues/1558#issuecomment-826637397


We have also made some efforts to make Kubeflow work better with KFServing out-of-the box, which will be included in version 1.3.1:
https://github.com/kubeflow/kubeflow/issues/5965
https://github.com/kubeflow/kubeflow/pull/5848
