### ISSUE TITLE
Automate manifests syncing from other repos

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#1906]
### Problem Statement

Currently, we sync manifests by hand: https://github.com/kubeflow/manifests/issues/1775
Automate the process with a python script.

**Comment by DavidSpek** [comment]
@yanniszark I've got another idea for implementing automation to do this that I wanted to bring up in the meeting later. This is mentioned in https://github.com/kubeflow/manifests/issues/1874 and we discussed it on a few other issues as well.

**Comment by thesuperzapper** [comment]
@yanniszark I agree with @DavidSpek here, we should aim to not duplicate the actual manifests, but reference tags/commit-hashes of the upstream repos, as this would allow us to simply change/update the reference, rather than building lots of infrastructure to copy the code.

A method for this is discussed in issue: https://github.com/kubeflow/manifests/issues/1874

**Comment by yanniszark** [comment]
@thesuperzapper thanks for referencing the proposal in #1874 for more context. Let's keep the discussion about the proposal for changing the way we reference manifests in #1874 and keep this issue about automating an established process that we already do by hand, not for introducing something new.
