### ISSUE TITLE
Error with the installation of Kubeflow stack 

### ISSUE THREAD

**Issue by EUCHI1996** [kubeflow/manifests#1909]
Hello,

I'm trying to install kubeflow 1.3 on my AKS Cluster (3 nodes) with this command : while ! kustomize build example | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done. But it's still running for 3 hours or 4 hours and the installation it fails.
![image](https://user-images.githubusercontent.com/57757186/122474596-c07e3100-cfc3-11eb-9e2d-6565af5ca289.png)

Please can anyone help me to resolve this issue ?

**Comment by ashokbalaraman** [comment]
@EUCHI1996 :  I am running into a similar issue, but slightly different error.

validatingwebhookconfiguration.admissionregistration.k8s.io/validation.webhook.serving.knative.dev unchanged
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request

**Comment by EUCHI1996** [comment]
@ashokbalaraman  : Yes, me too i get this issue.
I wish that the kubeflow team we help us to resolve this issue.

**Comment by rc-coderepo** [comment]
If you are using default example kubeflow install you might have to run this command multiple times before the installation would complete. This is because there are lot of dependencies like cert-manager,istio-system,knative,auth.... before the actual kubeflow installation can start. In the backgroud the installation is pulling lot of images from registry and that will also consume some time which is another reason for the installation failure.

You can follow the instruction to install components individually instead of all at once. This will also help you trace more accurate error that is causing this problem.
