### ISSUE TITLE
Kubeflow installation Error.

### ISSUE THREAD

**Issue by EUCHI1996** [kubeflow/manifests#1918]
Hello,
I'm trying to deploy Kubeflow, on AKS cluster using this github repo : https://github.com/kubeflow/manifests/tree/v1.3-branch.
but when i run this command : while ! kustomize build example | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done
it remains in a loop without installing kubeflow.
![image](https://user-images.githubusercontent.com/57757186/123312260-6122a280-d528-11eb-8566-0740de9a6ef8.png)

![image](https://user-images.githubusercontent.com/57757186/123312363-87484280-d528-11eb-88eb-c739c6f9ece0.png)

**Comment by rc-coderepo** [comment]
If you are using default example kubeflow install you might have to run this command multiple times before the installation would complete. This is because there are lot of dependencies like cert-manager,istio-system,knative,auth.... before the actual kubeflow installation can start. In the backgroud the installation is pulling lot of images from registry and that will also consume some time which is another reason for the installation failure. 

 **while ! kustomize build example | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done** 

You can follow the instruction to install components individually instead of all at once. This will also help you trace more accurate error that is causing this problem.

**Comment by RaphPfister** [comment]
Hi @rc-coderepo. I am myself trying to deploy kubeflow on an on-prem k8s cluster. I understand the point of retrying several time but the subsequent behaviour makes deploying kubeflow really hard task.
1) How can I distinguish an issue with my k8s install and the dependencies you mentionned not yet being deployed ?
2) At what point should I be worried that I have an issue on my side ? E.g. should I wait for 2 mins ? 45 mins ? A few days ?
