### ISSUE TITLE
Error while cloning or extracting Manifest Folder or Repo!

### ISSUE THREAD

**Issue by DARK-art108** [kubeflow/manifests#1928]
I am cloning the _kubeflow/manifests_ Repository but I always get the below error, even when extracting the zip after download, it stuck on the same error. Is it is a bug or any solution to fix it!

`error: invalid path 'tests/stacks/aws/application/cert-manager-kube-system-resources/test_data/expected/rbac.authorization.k8s.io_v1beta1_role_cert-manager-cainjector:leaderelection.yaml'`

![CAP](https://user-images.githubusercontent.com/53623244/123991083-04236280-d9e8-11eb-9961-96f99c265194.PNG)

**Comment by rc-coderepo** [comment]
one reason this could happen if you are cloning to a folder that is set to sync on one drive cloud storage on windows.

**Comment by asongent** [comment]
I think you are trying to clone a specific/particular branch.  To do that, run.
```bash
git clone --branch <branch-name> https://github.com/kubeflow/manifests.git
```
Example: If you want to clone `v0.6-branch`,  which is an `active` branch in that repo, run:
```bash
git clone --branch v0.6-branch https://github.com/kubeflow/manifests.git
```

If it fails, run the following command in a git-initialized repo and try again.
```bash
git config core..protectNTFS false
```

**Comment by asongent** [comment]
I think you are trying to clone a specific/particular branch.  To do that, run.
```bash
git clone --branch <branch-name> https://github.com/kubeflow/manifests.git
```
Example: If you want to clone `v0.6-branch`,  which is an `active` branch in that repo, run:
```bash
git clone --branch v0.6-branch https://github.com/kubeflow/manifests.git
```

If it fails, run the following command in a git-initialized repo and try again.
```bash
git config core.protectNTFS false
```

**Comment by asongent** [comment]
I think you are trying to clone a specific/particular ***branch***.  To do that, run:
```bash
git clone --branch <branch-name> https://github.com/kubeflow/manifests.git
```
**Example**: If you want to clone `v0.6-branch`  **(which is an `active`  branch of  [**kubeflow/manifets**](https://github.com/kubeflow/manifests/branches/all) repo as of now)**, run:
```bash
git clone --branch v0.6-branch https://github.com/kubeflow/manifests.git
```

If it fails, run the following command in a **git-initialized *directory*** and try again.
```bash
git config core.protectNTFS false
```

**Comment by goswamig** [comment]
@DARK-art108 are u still facing the issue ? 
I would recommend to clone the manifest repo from [here](https://github.com/awslabs/kubeflow-manifests/tree/v1.3-branch/distributions/aws/examples), if you're installing any further >=1.3.x

**Comment by HWiese1980** [comment]
I think this is due to the fact that there's a colon in the filename. Windows does not allow that.

**Comment by juliusvonkohout** [comment]
I think this is a valid issue. Can someone provide a PR ?

**Comment by juliusvonkohout** [comment]
@david-thrower

**Comment by david-thrower** [comment]
@juliusvonkohout  and maintainers:

Sorry for the verbose response: 

- In the branch main, this directory manifests/tests/stacks appears no longer there. This was committed on #1410 from https://github.com/PatrickXYS/manifests/tree/yao_aws_account. I haven't traced the fate of this file yet.
- It may be a moot issue for branch main / the current release, but may be something worth pushing a patch to any maintained affected legacy branches if otherwise indicated. **With that said, however**:
  - This file is in the dir: 'tests/stacks/aws/application/cert-manager-kube-system-resources/test_data/expected' 
  - With that nomenclature, I suspect that if the file is a source of ground truth for the test `tests/stacks/aws/application/cert-manager-kube-system-resources/kustomize_test.go`, so if the test is looking for a file with this name, changing the file name to sanitize the ':' I suspect may have deleterious effects [making the test fail] if the test is expecting this file **and is considering the file name**, not just the content. To make that work, the test may need to be re-written as well.

- Options:
  1. Close as `resolved` or `won't fix`; Dis recommend running this version on Windows, recommend using a VM / Cloud Shell environment. 
  2. Create a branch from this branch for a Windows support minor version, if there is anyone with a business need for this version for a legacy support purpose.  On this branch, remove the test altogether, with a warning that we recommend Windows users that if possible they should run the legacy version in a VM or an environment like `cloud shell (r)` or their cloud / managed stack vendor's equivalent.
  4. Rename the file to sanitize the ':' and rewrite the test `tests/stacks/aws/application/cert-manager-kube-system-resources/kustomize_test.go` to match file found in this folder by suitable regex pattern and expect it to have the expected content.
  5. I suspect (1) is the indicated disposition, unless we have a legacy support policy going back that far.  If (1) is done, these notes will hopefully be found by anyone still needing it and affected.

**Comment by juliusvonkohout** [comment]
@david-thrower  thank you, closing issues and PRs is also very important

/close
