### ISSUE TITLE
Update kfp-tekton apps for Kubeflow 1.4 release

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/manifests#2003]
For Kubeflow 1.4 release, we want to update the kfp-tekton upstream apps to the latest kfp-tekton 1.0.0 release
https://github.com/kubeflow/kfp-tekton/tree/v1.0.0/manifests/kustomize

This app will be used in the IBM Cloud and OpenShift distribution. We can also create the update PR to kubeflow/manifests if needed. Thank you in advance.

cc @kimwnasptd @elikatsis @yhwang

**Comment by kimwnasptd** [comment]
Hi @Tomcli, thanks for the update.

Under normal circumstances this update should not get merged since we are deep into the [`Feature Freeze`](https://github.com/kubeflow/manifests/tree/master/docs/releases/release-1.4#timeline) phase and it's two minor version up from the [previous release](https://github.com/kubeflow/manifests/tree/v1.3.1/#kubeflow-components-versions). This update should take place in the original issue when the release team asked for a sync from the Pipelines WG https://github.com/kubeflow/manifests/issues/1959.

The release team can also help to avoid such cases in the future by pinging WG subprojects owners as well, and not just WG owners, to ensure everyone is in sync. I think a mail in the mailing list could also help in reaching out to people who might not be closely following GitHub.

So considering the fact that :
1. it's the first time we have a more structured release
2. the release team also didn't give an explicit ping to the subproject's owners

I'm OK with merging this update **just for this release.** But in the future please provide this update before the Feature Freeze phase starts, where all WGs provide an update for their manifests, in order for the component to be updated in a future release.

We (release team) will also try our best to ensure all WGs are in sync with the different phases and avoid such situations in the future :slightly_smiling_face: 

@Tomcli I can PR the manifests update and you can help reviewing/merging them.
