### ISSUE TITLE
Duplicate keys in profiles manager.yaml

### ISSUE THREAD

**Issue by mwoodbri** [kubeflow/manifests#2261]
746c523 introduced duplicate `livenessProbe` and `ports` keys in [apps/profiles/upstream/manager/manager.yaml](https://github.com/kubeflow/manifests/blame/master/apps/profiles/upstream/manager/manager.yaml#L44-L57) - the file is now invalid YAML

**Comment by juangon** [comment]
@kimwnasptd

**Comment by kimwnasptd** [comment]
Hmm, it looks like we previously had the port 8080 for the `livenessProbe`, which was typed by hand.

But after the upgrade to Kubebuilder V3 https://github.com/kubeflow/kubeflow/pull/6491 we ended up with defining duplicate `livenessProbe` for the manager container.

Since we configure the manager [to use the port](https://github.com/kubeflow/kubeflow/blob/v1.6-branch/components/profile-controller/main.go#L90) `9876` for the probes I would suggest to keep these probes and remove the `livenessProbe` for port `8080`. 

Also, note that the manifests repo serves as a central copy of all manifests. Any changes will need to happen to the corresponding repos. So in this case `kubeflow/kubeflow`

**Comment by mwoodbri** [comment]
https://github.com/kubeflow/kubeflow/pull/6604
