### ISSUE TITLE
ArgoCD deployment

### ISSUE THREAD

**Issue by Syntax3rror404** [kubeflow/manifests#2374]
How can I install kubeflow with ArgoCD?

**Comment by jbottum** [comment]
/kind feature request
/area installation
/priority p2

@Syntax3rror404 thanks for your request.   Unless I am missing something, this pattern is not supported i.e. as you probably have seen, the community has developed a kustomize installation pattern.    there is some work on helm but that is not developed or supported.   We can bring this request up in the Community meeting but it probably is a question for the Manifest Working group meetings.    I suspect an Argo CD installation pattern would be a XXL sized feature, but willing to see what the community says.     @kubeflow/wg-manifests-leads

**Comment by Syntax3rror404** [comment]
A helm installation option would be perfect and would make the installation much easier. Helm is state of the art for installing kubernetes apps. Helm apps can also deployed with argo.

**Comment by jbottum** [comment]
You might check here: https://github.com/kubeflow/kubeflow/issues/3173

**Comment by thesuperzapper** [comment]
@Syntax3rror404 you will be very interested in the new version of [ArgoFlow](https://github.com/argoflow/argoflow) that @Talador12 and I are working on.

The current repo is quite messy and only supports Kubeflow 1.3, but we have a working version for 1.6+ that we are testing.

**Comment by Syntax3rror404** [comment]
@thesuperzapper I also seen argoflow, but there is no commit since two years. Why is it so imposible to install kubeflow right now? For normal applications I can set up a values file and fire helm against my cluster and the app comes up?

**Comment by agilgur5** [comment]
So ArgoCD does [support Kustomize](https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/). Several teams I work with have used that pattern to install it. It is pretty complicated to set-up nonetheless, especially if you have some of the dependencies already in your cluster and configured (e.g. we use Argo Workflows and Istio independently of Kubeflow).

Better organization around this and a Helm chart would certainly be preferable! I'd like to contribute a Helm chart(s) per my comment in https://github.com/kubeflow/kubeflow/issues/3173#issuecomment-1622742413 🙂 
Would think that would belong here in the `manifests` repo

**Comment by thesuperzapper** [comment]
So... 

Thanks for everyone's patience. Over the last few years I have been building [deployKF](https://www.deploykf.org/), it's effectively a reimagined version of Argoflow, but it's also SO much more than that too.

I am very excited for you all to try it, a crazy amount of work has been required, spanning multiple years, but I think it will completely change how open-source ML platforms are built on Kubernetes.

The first public beta will very likely drop tomorrow (but please don't get too mad if it takes a few more days, you will understand when you get to try it). 

❤️ ❤️ ❤️

**Comment by thesuperzapper** [comment]
Hi everyone, I am very excited to share the first release of deployKF! 

## Try it out here: https://github.com/deployKF/deployKF

### Why you should care.

With deployKF, it's WAY easier to configure things, because __everything has a config value__ (no more manual patches):

- [defining static user logins](https://github.com/deployKF/deployKF/blob/v0.1.0/generator/default_values.yaml#L360-L383)
- [connecting with identity providers like Microsoft AD, Okta, GitHub, Google Workspace, etc](https://github.com/deployKF/deployKF/blob/v0.1.0/generator/default_values.yaml#L385-L396)
- [defining users/profiles/groups](https://github.com/deployKF/deployKF/blob/v0.1.0/generator/default_values.yaml#L747-L810)
- [connecting Kubeflow Pipelines with S3](https://github.com/deployKF/deployKF/blob/v0.1.0/generator/default_values.yaml#L1640-L1675)
- [connecting Kubeflow Pipelines with an existing MySQL db](https://github.com/deployKF/deployKF/blob/v0.1.0/generator/default_values.yaml#L1677-L1691)
- [configuring Kubeflow Notebooks with custom images](https://github.com/deployKF/deployKF/blob/v0.1.0/generator/default_values.yaml#L1252-L1291)
- [exposing the main istio gateway as a LoadBalancer or with an Ingress](https://github.com/deployKF/deployKF/blob/v0.1.0/generator/default_values.yaml#L621-L628)
- etc.

We have patched LOTS of security issues, many of which can't be easily fixed in the upstream manifests:

- All secrets are randomly generated at install time, rather than being hardcoded in manifests.
- Reduced attack vectors compared to Kubeflow Manifests, particularly in Istio configurations.
- Uses Istio with [distroless images](https://istio.io/latest/docs/ops/configuration/security/harden-docker-images/) by default.
- MinIO (or S3) access keys are isolated to each profile, and scoped to the minimum required permissions.
- Supports using [AWS IRSA](https://github.com/deployKF/deployKF/blob/v0.1.0/generator/default_values.yaml#L1651-L1668) instead of S3 access keys.
- _(some redacted stuff)_

The whole design of deployKF is focused on creating enterprise-ready ML Platforms which are __actually possible to maintain__ in the long term, we have:

- In-place upgrades (bring your old custom values files to new versions, we aim to not break backward compatibility)
- Changes to configs/secrets will automatically restart the affected services
- GitOps with the industry standard, ArgoCD (note, support for other CD tools will come, and are even making a native installer that does not require GitOps)

deployKF is __more than just Kubeflow__, we aim to support all leading open ML & Data tools, for example:

- [MLflow Model Registry](https://www.deploykf.org/reference/future-tools/#mlflow-model-registry)
- [Apache Airfow](https://www.deploykf.org/reference/future-tools/#apache-airflow)
- [Feast](https://www.deploykf.org/reference/future-tools/#feast)
- _(so many more, see the [full list here](https://www.deploykf.org/reference/future-tools/))_

❤️  deployKF has been a long labor of love, with work spanning back at least 3 years! I am so excited to see how everyone uses it, and how the industry reacts to the best ML Platform being a free and open-source tool!

**Comment by Syntax3rror404** [comment]
deployKF are not solving my problem because I need a helm chart.

**Comment by thesuperzapper** [comment]
Thanks for reminding me about this issue.

As I believe [deployKF](https://www.deploykf.org/) resolves the issue around deploying Kubeflow with ArgoCD, I will be closing this issue for now. If anyone in the future creates an alternative solution, please feel free to raise it here.

Also, I would also like to draw everyone's attention to the [Kubeflow](https://github.com/kubeflow/community/blob/master/CODE_OF_CONDUCT.md) and [CNCF](https://github.com/cncf/foundation/blob/main/code-of-conduct.md) codes of conduct, as consistently breaking them may result in being banned from this repo.

/close
