### ISSUE TITLE
Notebook connect error

### ISSUE THREAD

**Issue by xiabo2011** [kubeflow/manifests#2438]
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/8590104/230828137-387cf2d1-3ff2-4df9-8889-d951ad972d28.png">
After I click "connect" button, it jump to new web page with URI /notebook, but got this error message 

`upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111`

Does anyone know what is the problem? Notebook related pod running successfully

**Comment by xiabo2011** [comment]
![image](https://user-images.githubusercontent.com/8590104/233255875-8c7745a1-aada-48d2-9c5e-1a2cfa388e9a.png)

I got this error in pod logs. Does anyone know how to  solve this problem? Thanks

**Comment by skuchipu** [comment]
Can you let us know how this is solved

**Comment by BOBO-ZzB** [comment]
Hello, I also encountered the same problem. How did you solve it? Please consult me

**Comment by xiabo2011** [comment]
After I change it to IP address directly instead of using nginx, I could connect the notebook

**Comment by BOBO-ZzB** [comment]
Thank you. I will try it out


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubeflow/manifests"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月1日(星期四) 晚上10:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kubeflow/manifests] Notebook connect error (Issue #2438)





 
After I change it to IP address directly instead of using nginx, I could connect the notebook
