### ISSUE TITLE
[kubeflow 1.8] KFP and Kubeflow 1.8

### ISSUE THREAD

**Issue by DnPlas** [kubeflow/manifests#2446]
Hi @kubeflow/wg-pipeline-leads

The 1.8 release team will use this tracking issue to coordinate the integration of KFP with Kubeflow 1.8.

Please note that communications (announcements, updates, questions, follow ups, etc.) will be done through kubeflow/manifests#2442 exclusively, this issue will be closed once the release team gathers the initial information from the WG.

Heads up that the proposed feature freeze is Aug 2nd, 2023, but the date is still subject to agreement and discussed [here](https://github.com/kubeflow/community/pull/621). Feel free to comment on the issue for suggestions. We will be sharing the finalised timeline before May 8th, 2023.

To prepare for the release, please provide answers to the following questions:

1. What version of KFP would you like to include for the 1.8 release?
2. Could you provide a branch/tag for this version if you have it already? (note: It doesn't have to be final)
3. Can you share a link to all open / work in progress issues that you're expecting to include in your next version?
4. Is @kubeflow/wg-pipeline-leads   updated? Who would be the main point of contact of this WG and what communication channel(s) do you folks prefer (e.g. slack, email, gh issue)?
5. If you're using the following dependencies, could you provide the versions you'll be supporting for each dependency?

* Knative
* Istio
* Kubernetes
* Cert-Manager
* Kustomize

The release team WG liaison for KFP is @Davidnet and you can keep track of high-level release updates in kubeflow/manifests#2442

**Comment by Davidnet** [comment]
I want this to be assigned to be please @DnPlas I am going to start my research

**Comment by Davidnet** [comment]
The following are responses gathered by asking in Slack, emails, and the documents presented in the kubeflow community meetings: 

- What version of KFP would you like to include for the 1.8 release?
KFP is mostly focus on the release of the v2.x.x versions, for which the 2.0 official version should be released in the end of May. [kanban board](https://github.com/orgs/kubeflow/projects/57/views/1)


- Could you provide a branch/tag for this version if you have it already? (note: It doesn't have to be final)
Group seems to be working on the [main branch ](https://github.com/kubeflow/pipelines) and the release pages and as May15th the last prerelease for v2 is [v2.0.16b](https://github.com/kubeflow/pipelines/tree/2.0.0b16)

- Can you share a link to all open / work in progress issues that you're expecting to include in your next version?
Same as first question, [kanban board](https://github.com/orgs/kubeflow/projects/57/views/1)

- Is @kubeflow/wg-pipeline-leads updated? Who would be the main point of contact of this WG and what communication channel(s) do you folks prefer (e.g. slack, email, gh issue)?
Lead member said is changing the members at [link](https://github.com/kubeflow/community/blob/master/wg-pipelines/README.md), only one member needs to be removed since he moved out to another project in google (Pavel - no, he moved on to a different team within Google).

I have asked for clarification on the official channels of communications, at this moment we used slack and email (will define this in the future)

- If you're using the following dependencies, could you provide the versions you'll be supporting for each dependency?

> Knative:kfp doesn't have a dependency or support relationship with knative. I don't foresee any compatible or incompatible changes from any previous version.
> Isto: TBD
> Kubernetes: Their test run on the release of GCP kubernetes chanel. They could support the latest -1 version because of GCP. Their tests run on stable and they can also run tests on rapid. So by Aug they should have tested on 1.24 (GCP stable) and 1.26 (GCP rapid). They could even support 1.27 depending on the rapid channel.
> Cert-Manager: TBD
> Kustomize: I cannot seem to find any dependency of kfp with kustomize, I will leave it as a TBD.

I will also update this as soon as the maintainers change and if any info changes accordingly.
