### ISSUE TITLE
KF 1.7 changes to spawner_ui_config.yaml have no effect

### ISSUE THREAD

**Issue by ckmeichs** [kubeflow/manifests#2526]
The config file controls the parameters of the jupyter-web-app for starting notebooks. We have there under 1.6 various images and especially MIG GPUs. With 1.7 these entries no longer have any effect.
Is there a solution or any workaround?

**Comment by annajung** [comment]
Hi @ckmeichs, this issue is related to the notebook component, not manifest.

There seems to be a similar discussion in the issue https://github.com/kubeflow/kubeflow/issues/7051. Please add on or create a new issue under kubeflow/kubeflow.

Feel free to close out the issue once the problem has been transferred to the correct repo. thanks!

**Comment by ckmeichs** [comment]
As recommended, I'm closing the issue
