### ISSUE TITLE
Could not find CSRF cookie XSRF-TOKEN in the request V1.7

### ISSUE THREAD

**Issue by SANJAY-NT** [kubeflow/manifests#2594]
when creating a model server over HTTP, I encountered the error.
[403] Could not find CSRF cookie XSRF-TOKEN in the request. http://172.16.40.233:30828/kserve-endpoints/api/namespaces/kubeflow-user-example-com/inferenceservices

Kubeflow version 1.7

**Comment by SANJAY-NT** [comment]
Anyone have any solution for this issue.

**Comment by juliusvonkohout** [comment]
1.7 is not supported anymore. We are at 1.8 and targeting 1.9.

**Comment by SANJAY-NT** [comment]
@juliusvonkohout  where can find the details related to kubeflow and its plans future (targets) .

**Comment by juliusvonkohout** [comment]
Here is some information https://github.com/kubeflow/manifests/issues/2600 especially https://github.com/orgs/kubeflow/projects/61/views/1

https://github.com/kubeflow/manifests/issues also contains some 1.9 roadmaps

Open source is free as in free speech, not free as in free beer ;-) 
So we mostly support the current version and you can get free (and sometimes not correct) help on the slack channel.

Github is more for refined bug reports and contributors that want to do PRs. There are also commercial distributions and paid support for people who do not want to contribute.

The topic you are talking about is also known, but might belong to kubeflow/kubeflow instead of kubeflow/manifets.
If you want to contribute feel free to reach out on slack to me.
