### ISSUE TITLE
Dex Bad request for custom user

### ISSUE THREAD

**Issue by tzabbi** [kubeflow/manifests#2812]
### Validation Checklist

- [X] Is this a Kubeflow issue?
- [X] Are you posting in the right repository ?
- [X] Did you follow the installation guide https://github.com/kubeflow/manifests?tab=readme-ov-file ?
- [X] Is the issue report properly structured and detailed with version numbers?
- [ ] Is this for Kubeflow development ?
- [X] Would you like to work on this issue?
- [ ] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

1.9

### Describe your issue

Custom user in kubeflow is unable to login because of redirection error: 

Bad request: Unregistered redirect_uri ("/oauth2/callback").
![image](https://github.com/user-attachments/assets/0f9147b0-dbb5-4f47-8bc2-eafefbaf2226)

I patched configmap and secret of dex with credentials for new user and this happens.

### Steps to reproduce the issue

Patch "/common/dex/base/config-map.yaml" and "/common/dex/base/dex-passwords.yaml".

**Comment by kromanow94** [comment]
As described in this comment, https://github.com/kubeflow/manifests/pull/2815#issuecomment-2247287964, this is probably related to the Kubeflow Instance installation using the dex definition from `common/dex/base` (or `common/dex/overlays/istio`)  instead of the `dex/overlays/oauth2-proxy` as in the `example/kustomization.yaml`.
