### ISSUE TITLE
v0.7-branch: cherry-pick oidc-authservice and cert-manager PRs for kfctl_existing_arrikto

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#616]
Cherry pick the following PRs so that kfctl_existing_arrikto (kfctl_istio_dex) can use the v0.7-branch.
* #529 (cherry pick in #615)
* #549 (cherry pick in #617)

**Comment by jlewi** [comment]
@yanniszark Can you provide me a little bit more context? I tried looking through the linked issues and PRs but couldn't find an overarching explanation of the feature or bug being addressed here.

My high level question is what's the motivation for cherry-picking these changes onto the v0.7-branch? Especially given that next week is Kubecon and we just published our 0.7 blog post is it possible these changes could break 0.7 just as lots of people try it?

**Comment by jlewi** [comment]
@yanniszark regarding this comment
https://github.com/kubeflow/manifests/pull/447#issuecomment-553682723

Could you please summarize the current state of the the v0.7 release of existing_arrikto.

/cc @krishnadurai

**Comment by krishnadurai** [comment]
@jlewi @yanniszark 

This is what I gather from looking at the 0.7 branch:

Existing Arrikto is pinned on a commit from master branch for downloading manifests:

https://github.com/kubeflow/manifests/blob/v0.7-branch/kfdef/kfctl_existing_arrikto.0.7.0.yaml#L329

Unlike GCP IAP config, which is referring to 0.7 branch:

https://github.com/kubeflow/manifests/blob/v0.7-branch/kfdef/kfctl_gcp_iap.0.7.0.yaml#L398

These commits referred to by @yanniszark are a necessary part of Istio-Dex configuration are now not a part of the 0.7 release branch. That's the reason why existing_arrikto config isn't pointing to 0.7 branch.

Now, this has introduced a complication. Fixes or additions to existing_arrikto config can't go to the 0.7 branch since it is referring to commits from master.

To correct this, it would be necessary for us to cherry-pick these two commits. Which should have been done while releasing the existing_arrikto config for v0.7.

Both these commits (Cert-Manager and OIDC AuthService) affect Dex based manifests.

**Comment by yanniszark** [comment]
Closing since all PRs were merged.
/close
