### ISSUE TITLE
Profile controller doesn't have GCP permission to bind workload identities

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/manifests#663]
Hi, when trying to use profile controller (when creating a new profile), I got this error in profiles-manager:
```
2019-12-12T02:28:48.124Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "profile", "request": "/test-yuan", "error": "googleapi: Error 403: Permission iam.serviceAccounts.getIamPolicy is required to perform this operation on service account projects/ml-pipeline-dogfood/serviceAccounts/multiuser-kfp-only-admin@ml-pipeline-dogfood.iam.gserviceaccount.com., forbidden"}
```

I tried adding roles/iam.serviceAccountAdmin to multiuser-kfp-only-admin and it works afterwards. I believe this is a missing GCP permission that should be added to kubeflow-admin service accounts in https://github.com/kubeflow/manifests/blob/master/gcp/deployment_manager_configs/iam_bindings_template.yaml#L10

https://cloud.google.com/iam/docs/understanding-roles#service-accounts-roles

**Comment by jlewi** [comment]
@kunmingg can you take a look at this?

**Comment by gaoning777** [comment]
BTW, the profile controller we deployed is based on the master instead of the 0.7. Could it be that the 0.7 works but there's feature regression on the master?

**Comment by kunmingg** [comment]
Hi Yuan,

Currently if profile controller is deployed with kfctl:
* profile controller will be using `<deploy>-admin` gcp identity
* default `gcpServiceAccount` in profile `WorkloadIdentity` will be `<deploy>-user` gcp identity.
* kfctl will make `<deploy>-admin` the owner of `<deploy>-user`: https://github.com/kubeflow/kfctl/blob/f3d60cff40406f656621349977499896b070d6b8/pkg/kfapp/gcp/gcp.go#L857

So for example if we want to use `multiuser-kfp-only-user@ml-pipeline-dogfood.iam.gserviceaccount.com` in profile, we can grant `multiuser-kfp-only-admin@` owner permission to above service account.

Granting `roles/iam.serviceAccountAdmin` works as well, but it shares access to all service accounts instead of the one we are using.

**Comment by kunmingg** [comment]
Can you try update your profile spec with `multiuser-kfp-only-user@ml-pipeline-dogfood.iam.gserviceaccount.com`?

**Comment by Bobgy** [comment]
@kunmingg Thank you for the explanation. Now I understand the design choice.

When multiple users are all using `multiuser-kfp-only-user@ml-pipeline-dogfood.iam.gserviceaccount.com`. There's no GCP permission difference.

If we also want to separate GCP permission for different users and let Profile controller bind workload identity automatically, we have two choices:
1. Let <deploy>-admin own the extra service accounts we want to use
2. Give <deploy>-admin roles/iam.serviceAccountAdmin, so it will have access to all service accounts in the project.

1. is more secure, no extra permission granted at all
2. is easier to use, no manual work after initial set up

Maybe both approaches may have some use cases. I think we need some documentation about this, because also separating GCP permissions sound like something users caring about multi user support will need naturally.

**Comment by gaoning777** [comment]
@kunmingg Thanks.
The Option 1, as it is right now, is secure and good for default configuration. A good documentation is all that is needed such that admin of the cluster can grant reasonable permissions to the admin gsa in a particular k8s cluster. 
WDYT?

**Comment by kunmingg** [comment]
Agree, will update doc on website for this use case.

**Comment by Bobgy** [comment]
Thank you! That would be helpful.
