### ISSUE TITLE
Update Metadata Docker images for Kubeflow 1.0?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#807]
Do we need to update the docker images used by metadata for 1.0 or are the images in
https://github.com/kubeflow/manifests/blob/master/metadata/base/kustomization.yaml

Up to date.

Once kubeflow/testing#587 we should be able to just add the requisite specs to that file to auto-build and update the docker images used by metadata.

/assign @zhenghuiwang 
/cc @avdaredevil

**Comment by zhenghuiwang** [comment]
For Metadata Go backend, there isn't any change since v0.7 so no need to build a new image for KF1.0.

For MLMD gRPC server, the manifests file is just updated to use the latest version v0.21.1.

Automatically building the images for frontend and backend is a good prerequisite, but I guess it is not blocking KF1.0 releases.

**Comment by jlewi** [comment]
Thanks @zhenghuiwang so is there any remaining work for 1.0 or can we close this issue?

**Comment by zhenghuiwang** [comment]
https://github.com/kubeflow/kfctl/pull/204 is the cherry-pick, but tests failed.
